---

output-format: text

allow-shorthand: false

ignore-patterns:
  - (^|/)\..+

pylint:
  disable:
    - bad-continuation

  options:
    max-locals: 17
    max-returns: 6
    max-branches: 13
    max-statements: 60
    max-parents: 7
    max-attributes: 7
    min-public-methods: 2
    max-public-methods: 20
    max-module-lines: 1000
    max-line-length: 99

mypy:
  options:
    ignore-missing-imports: true
    follow-imports: skip

pyroma:
  disable:
    - PYR06

mccabe:
  options:
    max-complexity: 13

pep8:
  disable:
   - W605

  options:
    max-line-length: 99
    single-line-if-stmt: n

pep257:
  disable:
    - D000
    - D107
    - D104
    - D203
    - D204
    - D205
    - D213
