sudo: false

cache: pip

matrix:
  include:
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.5

env:
  global:
    - PASS_VERSION=1.7.1

install:
  - export PREFIX=$HOME/.bin/usr PATH="$PATH:$HOME/.bin/usr/bin"
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install
  - pip3 install green coverage codacy-coverage requests zxcvbn

script:
  - make tests

after_success:
  - cd tests && coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email: false
